trigger:
- main

variables:
- group: cloudflare-workers
- name: WRANGLER_INSTALL_PATH
  value: /usr/local/bin/.wrangler 

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: wranglerConfiguration
  displayName: 'Download wrangler configuration'
  inputs:
    secureFile: '0c5f0e84-8576-4316-ba74-7ace49fb7942'
- task: CmdLine@2
  displayName: 'Setup wrangler configuration'
  inputs:
    script: |
      cp -f $(wranglerConfiguration.secureFilePath) .
- task: NodeTool@0
  displayName: 'Install latest Node.js LTS'
  inputs:
    versionSpec: '16.x'
- task: CmdLine@2
  displayName: 'Setup dependencies'
  inputs:
    script: |
      sudo -E yarn global add @cloudflare/wrangler
      yarn install
- task: CmdLine@2
  displayName: 'Build worker'
  inputs:
    script: |
      yarn build
- task: CmdLine@2
  displayName: 'Publish worker'
  inputs:
    script: |
      CF_ACCOUNT_ID=$(CF_ACCOUNT_ID) CF_API_TOKEN=$(CF_API_TOKEN) wrangler publish
